### PR TITLE
make it take a logger option

### PR DESCRIPTION
**Pull request by HenrikJoreteg**
Seems like something like this would work. We would just Just init a bucker logger first and pass it in. If nothing was passed, it just uses console.

### CODE REVIEW

**Comment by wraithgar** [comment]
Can we fall back to debug instead of console? I really don't want to throw console messages into middleware.

https://github.com/visionmedia/debug

var debug = require('debug')('andyet-express-auth');

logger = opts.logger || debug;

**Comment by legastero** [comment]
+1 either way for me; I'm not too bothered by falling back to console.

**Comment by HenrikJoreteg** [comment]
i'd rather fallback to a built-in than another 3rd party dependency.

I could see just falling back to no logging though.

**Comment by HenrikJoreteg** [comment]
i'm reading through debug docs. Makes sense to me now that i get it.

**Comment by HenrikJoreteg** [comment]
thing that sucks about debug is that everything is a console.error... hm...

**Comment by HenrikJoreteg** [comment]
The more I think about it, I think falling back to console makes the most sense since we're only logging out stuff on error conditions which follows the rule of silence: http://www.linfo.org/rule_of_silence.html

**Pull request merged**
